# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - test
  - build
  - container


variables:
  # fixed variables:
  DEST: "docker.gitlab.gwdg.de/${CI_PROJECT_PATH}"
  IMAGE_TAG: "${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}"
  IMAGE_NAME: "${DEST}:${IMAGE_TAG}"


sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

build:
  stage: build
  image: docker.io/node:latest
  script:
    - npm ci
    - npm run build
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: "30 days"
    paths:
      - .next/standalone

build_docker:
  stage: container
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  dependencies:
    - build
  before_script:
    - echo "Pushing image to ${DEST}"
    - DATE=$(date '+%Y-%m-%dT%H.%M.%S')
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination ${IMAGE_NAME}
